CUDA_VISIBLE_DEVICES=3,4 python src/train_bash.py \
    --stage rm \
    --do_predict \
    --flash_attn True\
    --model_name_or_path meta-llama/Llama-2-7b-hf \
    --vhead_oracle_path saves/Llama-2-7b-hf/truthful_qa_train/random/oracle \
    --finetuning_type full \
    --dataset_dir data \
    --dataset reward_bench_train \
    --template default \
    --output_dir saves/Llama-2-7b-hf/truthful_qa_train/random/oracle  \
    --per_device_eval_batch_size 4 \
    --fp16


CUDA_VISIBLE_DEVICES=0,1 python src/train_bash.py \
    --stage rm \
    --do_predict \
    --model_name_or_path meta-llama/Llama-2-7b-hf \
    --adapter_name_or_path saves/Llama-2-7b-hf/truthful_qa_train/random/oracle \
    --flash_attn True\
    --dataset reward_bench_train \
    --dataset_dir data \
    --template default \
    --output_dir saves/Llama-2-7b-hf/truthful_qa_train/random/oracle \
    --overwrite_output_dir \
    --overwrite_cache\
    --cutoff_len 1024 \
    --per_device_train_batch_size 4 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 4 \
    --lr_scheduler_type cosine \
    --logging_steps 10 \
    --warmup_steps 20 \
    --save_steps 1000 \
    --eval_steps 1000 \
    --evaluation_strategy steps \
    --learning_rate 5e-5 \
    --num_train_epochs 1 \
    --max_samples 100 \
    --val_size 0.1 \
    --ddp_timeout 1800000 \
    --plot_loss \
    --report_to none\
    --fp16